'use client'
import { useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import { useRouter } from 'next/navigation'
import Link from 'next/link'

export default function LoginPage() {
  const [email, setEmail] = useState('')
    const [password, setPassword] = useState('')
      const [error, setError] = useState('')
        const [loading, setLoading] = useState(false)
          const router = useRouter()
            const supabase = createClient()

              async function handleLogin(e: React.FormEvent) {
                  e.preventDefault()
                      setLoading(true)
                          setError('')
                              const { error } = await supabase.auth.signInWithPassword({ email, password })
                                  if (error) {
                                        setError(error.message)
                                              setLoading(false)
                                                  } else {
                                                        router.push('/dashboard')
                                                            }
                                                              }

                                                                return (
                                                                    <div className="min-h-screen bg-gray-50 flex items-center justify-center p-4">
                                                                          <div className="bg-white rounded-2xl shadow-sm border border-gray-100 w-full max-w-md p-8">
                                                                                  <div className="mb-8">
                                                                                            <h1 className="text-2xl font-semibold text-gray-900">Welcome back</h1>
                                                                                                      <p className="text-gray-500 mt-1">Sign in to your QuiDash account</p>
                                                                                                              </div>
                                                                                                                      {error && (
                                                                                                                                <div className="bg-red-50 text-red-600 text-sm p-3 rounded-lg mb-4">
                                                                                                                                            {error}
                                                                                                                                                      </div>
                                                                                                                                                              )}
                                                                                                                                                                      <form onSubmit={handleLogin} className="space-y-4">
                                                                                                                                                                                <div>
                                                                                                                                                                                            <label className="block text-sm font-medium text-gray-700 mb-1">Email</label>
                                                                                                                                                                                                        <input
                                                                                                                                                                                                                      type="email"
                                                                                                                                                                                                                                    value={email}
                                                                                                                                                                                                                                                  onChange={e => setEmail(e.target.value)}
                                                                                                                                                                                                                                                                className="w-full border border-gray-200 rounded-lg px-4 py-3 text-sm outline-none focus:border-purple-500"
                                                                                                                                                                                                                                                                              placeholder="you@example.com"
                                                                                                                                                                                                                                                                                            required
                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                                                                                                                                        <label className="block text-sm font-medium text-gray-700 mb-1">Password</label>
                                                                                                                                                                                                                                                                                                                                                    <input
                                                                                                                                                                                                                                                                                                                                                                  type="password"
                                                                                                                                                                                                                                                                                                                                                                                value={password}
                                                                                                                                                                                                                                                                                                                                                                                              onChange={e => setPassword(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                            className="w-full border border-gray-200 rounded-lg px-4 py-3 text-sm outline-none focus:border-purple-500"
                                                                                                                                                                                                                                                                                                                                                                                                                          placeholder="••••••••"
                                                                                                                                                                                                                                                                                                                                                                                                                                        required
                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="w-full bg-[#1A1035] text-white py-3 rounded-lg text-sm font-medium hover:opacity-90 disabled:opacity-50"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {loading ? 'Signing in...' : 'Sign in'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-center text-sm text-gray-500 mt-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Don't have an account?{' '}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Link href="/signup" className="text-purple-600 font-medium">Sign up</Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }