'use client'
import { useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import { useRouter } from 'next/navigation'
import Link from 'next/link'

export default function SignupPage() {
  const [email, setEmail] = useState('')
    const [password, setPassword] = useState('')
      const [fullName, setFullName] = useState('')
        const [error, setError] = useState('')
          const [loading, setLoading] = useState(false)
            const [success, setSuccess] = useState(false)
              const router = useRouter()
                const supabase = createClient()

                  async function handleSignup(e: React.FormEvent) {
                      e.preventDefault()
                          setLoading(true)
                              setError('')
                                  const { error } = await supabase.auth.signUp({
                                        email,
                                              password,
                                                    options: { data: { full_name: fullName } }
                                                        })
                                                            if (error) {
                                                                  setError(error.message)
                                                                        setLoading(false)
                                                                            } else {
                                                                                  setSuccess(true)
                                                                                      }
                                                                                        }

                                                                                          if (success) {
                                                                                              return (
                                                                                                    <div className="min-h-screen bg-gray-50 flex items-center justify-center p-4">
                                                                                                            <div className="bg-white rounded-2xl shadow-sm border border-gray-100 w-full max-w-md p-8 text-center">
                                                                                                                      <div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4">
                                                                                                                                  <span className="text-2xl">✅</span>
                                                                                                                                            </div>
                                                                                                                                                      <h2 className="text-xl font-semibold text-gray-900 mb-2">Check your email</h2>
                                                                                                                                                                <p className="text-gray-500 text-sm">We sent a confirmation link to <strong>{email}</strong>. Click it to activate your account.</p>
                                                                                                                                                                          <button
                                                                                                                                                                                      onClick={() => router.push('/login')}
                                                                                                                                                                                                  className="mt-6 w-full bg-[#1A1035] text-white py-3 rounded-lg text-sm font-medium"
                                                                                                                                                                                                            >
                                                                                                                                                                                                                        Go to login
                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                            <div className="min-h-screen bg-gray-50 flex items-center justify-center p-4">
                                                                                                                                                                                                                                                                  <div className="bg-white rounded-2xl shadow-sm border border-gray-100 w-full max-w-md p-8">
                                                                                                                                                                                                                                                                          <div className="mb-8">
                                                                                                                                                                                                                                                                                    <h1 className="text-2xl font-semibold text-gray-900">Create your account</h1>
                                                                                                                                                                                                                                                                                              <p className="text-gray-500 mt-1">Start building your fintech business today</p>
                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                              {error && (
                                                                                                                                                                                                                                                                                                                        <div className="bg-red-50 text-red-600 text-sm p-3 rounded-lg mb-4">
                                                                                                                                                                                                                                                                                                                                    {error}
                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                              <form onSubmit={handleSignup} className="space-y-4">
                                                                                                                                                                                                                                                                                                                                                                        <div>
                                                                                                                                                                                                                                                                                                                                                                                    <label className="block text-sm font-medium text-gray-700 mb-1">Full name</label>
                                                                                                                                                                                                                                                                                                                                                                                                <input
                                                                                                                                                                                                                                                                                                                                                                                                              type="text"
                                                                                                                                                                                                                                                                                                                                                                                                                            value={fullName}
                                                                                                                                                                                                                                                                                                                                                                                                                                          onChange={e => setFullName(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="w-full border border-gray-200 rounded-lg px-4 py-3 text-sm outline-none focus:border-purple-500"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      placeholder="Your full name"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <label className="block text-sm font-medium text-gray-700 mb-1">Email</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          type="email"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        value={email}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onChange={e => setEmail(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="w-full border border-gray-200 rounded-lg px-4 py-3 text-sm outline-none focus:border-purple-500"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  placeholder="you@example.com"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <label className="block text-sm font-medium text-gray-700 mb-1">Password</label>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      type="password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    value={password}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onChange={e => setPassword(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="w-full border border-gray-200 rounded-lg px-4 py-3 text-sm outline-none focus:border-purple-500"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              placeholder="Min. 8 characters"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            minLength={8}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          required
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      type="submit"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  disabled={loading}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className="w-full bg-[#1A1035] text-white py-3 rounded-lg text-sm font-medium hover:opacity-90 disabled:opacity-50"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {loading ? 'Creating account...' : 'Create account'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </form>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p className="text-center text-sm text-gray-500 mt-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Already have an account?{' '}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Link href="/login" className="text-purple-600 font-medium">Sign in</Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }